#!/bin/bash
set -e

# build
./gradlew clean build -x test

PROJECT_ROOT=$(pwd)
BUILD_PATH=$(ls $PROJECT_ROOT/build/libs/*.jar)
JAR_NAME=$(basename $BUILD_PATH)

# Copy To Server
scp $BUILD_PATH $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH

# Run Application
ssh $DEPLOY_USER@$DEPLOY_SERVER << EOF
sudo systemctl set-environment DATABASE_PW=$DATABASE_PW DATABASE_URL=$DATABASE_URL DATABASE_USER=$DATABASE_USER JWT_SECRET=$JWT_SECRET SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL IMAGE_FILE_PATH=$IMAGE_FILE_PATH PORT=$PORT DEPLOY_SERVER=$DEPLOY_SERVER KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID KAKAO_REDIRECTION_URI=$KAKAO_REDIRECTION_URI PORT=36071
sudo systemctl restart dudoji-server.service
EOF
